version: '3.9'

services:
  master:
    build: ./jmeter-master
    container_name: master
    tty: true # tty true make the docker image stay up even with nothing running
    volumes:
      - ./results:/results:rw
    networks:
      - jmeter-network
  slave:
    build: ./jmeter-slave
    tty: true
    networks:
      - jmeter-network

networks:
  jmeter-network:
